version: '3'
#new version
volumes:
  postgres_data:
      driver: local
services:
  postgres:
      image: postgres:14-alpine
      restart: always
      # ports:
      #   - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - uplbapp
  adminer:
      image: adminer
      restart: always
      ports:
        - 8500:8080
      networks:
        - uplbapp
  keycloak:
      image: quay.io/keycloak/keycloak:20.0.5
      restart: always
      environment:
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_URL_DATABASE: keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: password
        KC_DIR: ./
        KC_REALM: UPLB_APP_REALM
        KC_USERS: different_file
        KC_USERS_PER_FILE: 1000
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
        PROXY_ADDRESS_FORWARDING: true
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      command:
        - start-dev
      volumes:
        #exports
        - ./:/exports
        #certs
        - ./ssl/fullchain.pem:/etc/x509/https/tls.crt"
        - ./ssl/privkey.pem:/etc/x509/https/tls.key
        # THEMES
        - ./themes/uplbtheme:/opt/keycloak/themes/uplbtheme
        - ./themes/uplbtheme.v2:/opt/keycloak/themes/uplbtheme.v2
        - ./themes/uplbtheme.v3:/opt/keycloak/themes/uplbtheme.v3
        # PROVIDERS
        # 2FA Email
        - ./providers/niroj-keycloak-2fa-email-authenticator-1.0-SNAPSHOT.jar:/opt/keycloak/providers/niroj-keycloak-2fa-email-authenticator-1.0-SNAPSHOT.jar
        - ./providers/original-niroj-keycloak-2fa-email-authenticator-1.0-SNAPSHOT.jar:/opt/keycloak/providers/original-niroj-keycloak-2fa-email-authenticator-1.0-SNAPSHOT.jar
        #Alternate login
        - ./providers/attribute-login-provider-0.0.0-SNAPSHOT-javadoc.jar:/opt/keycloak/providers/attribute-login-provider-0.0.0-SNAPSHOT-javadoc.jar
        - ./providers/attribute-login-provider-0.0.0-SNAPSHOT-sources.jar:/opt/keycloak/providers/attribute-login-provider-0.0.0-SNAPSHOT-sources.jar
        - ./providers/attribute-login-provider-0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/attribute-login-provider-0.0.0-SNAPSHOT.jar
      ports:
        - 8282:8080
        - 443:8443
      depends_on:
        - postgres
      networks:
        - uplbapp
networks:
  uplbapp:
    driver: bridge
