version: '3'
#new version
volumes:
  postgres_data:
      driver: local
services:
  postgres:
      image: postgres:14-alpine
      restart: always
      # ports:
      #   - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - uplbapp
  adminer:
      image: adminer
      restart: always
      ports:
        - 8500:8080
      networks:
        - uplbapp
  keycloak:
<<<<<<< HEAD
<<<<<<< HEAD
      image: quay.io/keycloak/keycloak:latest
=======
      image: quay.io/keycloak/keycloak:22.0.4
>>>>>>> a9d4239bff6d8797dd0dd0c749f76cf2d095c857
=======
      image: quay.io/keycloak/keycloak:latest
>>>>>>> adaecfecef4f5ec9348a27f4dd6d83287496728d
      restart: always
      environment:
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_URL_DATABASE: keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: password
        KC_DIR: ./
        KC_REALM: UPLB_APP_REALM
        KC_USERS: different_file
        KC_USERS_PER_FILE: 1000
        KEYCLOAK_ADMIN: admin
        KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/fullchain.pem
        KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/privkey.pem
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
<<<<<<< HEAD
        # KC_HOSTNAME: https://localhost/auth
        # KEYCLOAK_FRONTEND_URL: https://keycloak.uplb.edu.ph/
        KC_PROXY: edge
        # KC_HOSTNAME_ADMIN_URL: https://keycloak.uplb.edu.ph/
        PROXY_ADDRESS_FORWARDING: 1
        # KC_TRANSACTION_XA_ENABLED: 0
=======
        PROXY_ADDRESS_FORWARDING: 1
        KC_FEATURES: account3,admin-api,account-api
        KC_METRICS_ENABLED: 1
        KC_HEALTH_ENABLED: 1
>>>>>>> a9d4239bff6d8797dd0dd0c749f76cf2d095c857
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      command:
        - start-dev
      volumes:
        #exports
        - ./:/exports
        #certs
        - ./ssl:/opt/keycloak/certs
        # THEMES
        - ./themes:/opt/keycloak/themes
        # PROVIDERS
        # 2FA Email
        - ./providers/niroj-keycloak-2fa-email-authenticator-1.0-SNAPSHOT.jar:/opt/keycloak/providers/niroj-keycloak-2fa-email-authenticator-1.0-SNAPSHOT.jar
        - ./providers/original-niroj-keycloak-2fa-email-authenticator-1.0-SNAPSHOT.jar:/opt/keycloak/providers/original-niroj-keycloak-2fa-email-authenticator-1.0-SNAPSHOT.jar
        #Alternate login
        - ./providers/attribute-login-provider-0.0.0-SNAPSHOT-javadoc.jar:/opt/keycloak/providers/attribute-login-provider-0.0.0-SNAPSHOT-javadoc.jar
        - ./providers/attribute-login-provider-0.0.0-SNAPSHOT-sources.jar:/opt/keycloak/providers/attribute-login-provider-0.0.0-SNAPSHOT-sources.jar
        - ./providers/attribute-login-provider-0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/attribute-login-provider-0.0.0-SNAPSHOT.jar
      ports:
<<<<<<< HEAD
        - 8282:8080
        - 8433:8443
=======
        - 8080:8080
        - 443:8443
>>>>>>> a9d4239bff6d8797dd0dd0c749f76cf2d095c857
      depends_on:
        - postgres
      networks:
        - uplbapp
networks:
  uplbapp:
    driver: bridge
